// lib/app/theme/app_colors.dart
import 'package:flutter/material.dart';

/// Design tokens for colors. Extracted from React SplashScreen computed/source.
abstract class AppColors {
  // --- Splash / Marketing palette ---
  static const Color splashBgStart = Color(0xFFFFFBFC);
  static const Color splashBg25 = Color(0xFFFFF5F7);
  static const Color splashBg50 = Color(0xFFFFEFF3);
  static const Color splashBg75 = Color(0xFFFCE8ED);
  static const Color splashBgEnd = Color(0xFFF5E0E7);

  static const Color primaryPink = Color(0xFFE91E63);
  static const Color primaryPurple = Color(0xFF9C27B0);
  static const Color pinkDark = Color(0xFFC2185B);
  static const Color purpleDark = Color(0xFF7B1FA2);
  static const Color pinkAccent = Color(0xFFF06292);
  static const Color pinkLight = Color(0xFFF48FB1);
  static const Color purpleAccent = Color(0xFFBA68C8);

  static const Color textPrimary = Color(0xFF4A1942);
  static const Color textSecondary = Color(0xFF6B2C4D);
  static const Color textMuted = Color(0xFF9C7B8A);

  static const Color success = Color(0xFF10B981);

  static const Color white = Color(0xFFFFFFFF);
  static const Color white70 = Color(0xB3FFFFFF);
  static const Color white60 = Color(0x99FFFFFF);
  static const Color white40 = Color(0x66FFFFFF);

  // --- Onboarding Intro (HeroBannerDemo) ---
  static const Color onboardingPageBg = Color(0xFFFFFFFF);
  static const Color onboardingHeadline = Color(0xFF7A3E55);
  static const Color onboardingBulletText = Color(0xFFA84968);
  static const Color onboardingSubtext = Color(0xFF8B4A65);
  static const Color onboardingThatsAll = Color(0xFFB05A78);
  static const Color onboardingValuePropRed = Color(0xFFE11D48);
  static const Color onboardingValuePropPink = Color(0xFFEC4899);
  static const Color onboardingValuePropPurple = Color(0xFFA855F7);
  static const Color onboardingPinkFill = Color(0xFFF9A8D4);
  static const Color onboardingRoseFill = Color(0xFFFB7185);
  static const Color onboardingCardBorder = Color(0x4DFBCFE8);
  static const Color onboardingCardBorderStrong = Color(0x80FB7185);
  static const Color onboardingGlobeBorder = Color(0x66FBCFE8);

  // --- Auth (Sign Up / Login) ---
  static const Color authBackBg = Color(0xFFEFE8FF);
  static const Color authWelcomeTitle = Color(0xFFE22B69);
  static const Color authSubtitle = Color(0xFF333333);
  static const Color authTabContainerBg = Color(0xFFF8F8F8);
  static const Color authTabInactiveText = Color(0xFF333333);
  static const Color authSocialButtonBg = Color(0xFFFFFFFF);
  static const Color authSocialButtonText = Color(0xFF333333);
  static const Color authDividerLine = Color(0xFFE5E5E5);
  static const Color authDividerText = Color(0xFFAAAAAA);
  static const Color authInputBg = Color(0xFFFFF2F6);
  static const Color authInputPlaceholder = Color(0xFFF28BA8);
  static const Color authInputBorder = Color(0xFFFECDD3);
  static const Color authInputFocusBorder = Color(0xFFE91E63);
  static const Color authFooterText = Color(0xB3666666);
  static const Color authErrorBg = Color(0xFFFEF2F2);
  static const Color authErrorBorder = Color(0xFFFECACA);
  static const Color authErrorText = Color(0xFFB91C1C);

  // --- User Type selection ---
  static const Color userTypeBgStart = Color(0xFFF3E8FF);
  static const Color userTypeBgMid = Color(0xFFFDF2F8);
  static const Color userTypeBgEnd = Color(0xFFFFE4E6);
  static const Color userTypeTitle = Color(0xFF6B21A8);
  static const Color userTypeTitleAccent = Color(0xFFE11D48);
  static const Color userTypeSubtitle = Color(0xFFF43F5E);
  static const Color userTypeCardBg = Color(0xCCFFFFFF);
  static const Color userTypeCardTitle = Color(0xFF6B21A8);
  static const Color userTypeCardDesc = Color(0xFF374151);
  static const Color userTypeCardBorder = Color(0x99FDA4AF);
  static const Color userTypeCardBorderSelected = Color(0xB3FB7185);
  static const Color userTypeCardBorderBusiness = Color(0x99C4B5FD);
  static const Color userTypeCardBorderBusinessSelected = Color(0xB3A78BFA);

  // --- Individual Profile Step 1 (Tell Cherish AI about yourself) ---
  static const Color profileStep1BgTop = Color(0xFFFBEFFF);
  static const Color profileStep1BgMid = Color(0xFFFDF5F8);
  static const Color profileStep1BgBottom = Color(0xFFFCEEF3);
  static const Color profileStep1BackBtnBg = Color(0xFFFFF2F6);
  static const Color profileStep1BackBtnIcon = Color(0xFFFB7185);
  static const Color profileStep1StepPillText = Color(0xFFFB7185);
  static const Color profileStep1Title = Color(0xFF1E293B);
  static const Color profileStep1Subtitle = Color(0xFF6B7280);
  static const Color profileStep1Label = Color(0xFF6B7280);
  static const Color profileStep1CardBg = Color(0xFFFFFFFF);
  static const Color profileStep1CardLabel = Color(0xFF1E293B);
  static const Color profileStep1RequiredAsterisk = Color(0xFFDC2626);
  static const Color profileStep1Helper = Color(0xFF9CA3AF);
  static const Color profileStep1InputBg = Color(0xFFFFFFFF);
  static const Color profileStep1InputBorder = Color(0xFFE5E7EB);
  static const Color profileStep1InputPlaceholder = Color(0xFF9CA3AF);
  static const Color profileStep1ChipText = Color(0xFF374151);
  static const Color profileStep1ChipBorder = Color(0xFFE5E7EB);
  static const Color profileStep1ChipSelectedBg = Color(0xFFFB7185);
  static const Color profileStep1PhotoCircleBorder = Color(0xFFFFC0CB);
  static const Color profileStep1PhotoCircleInner = Color(0xFFFFF2F6);
  static const Color profileStep1PhotoIcon = Color(0xFFFB7185);
  static const Color profileStep1RequiredHint = Color(0xFFDC2626);

  // --- Individual Step 2 (Add a loved one) ---
  static const Color lovedOneBgTop = Color(0xFFFDF2F8);
  static const Color lovedOneBgBottom = Color(0xFFFCE7F3);
  static const Color lovedOneBackBtnBg = Color(0xFFFFF2F6);
  static const Color lovedOneBackBtnIcon = Color(0xFFFB7185);
  static const Color lovedOneHeartCircleBg = Color(0xFFFB7185);
  static const Color lovedOneTitle = Color(0xFF1E293B);
  static const Color lovedOneSubtitle = Color(0xFFE11D48);
  static const Color lovedOnePhotoLabel = Color(0xFFFB7185);
  static const Color lovedOnePhotoCircleBg = Color(0xFFFFF2F6);
  static const Color lovedOnePhotoCircleBorder = Color(0xFFF9A8D4);
  static const Color lovedOnePhotoIcon = Color(0xFF64748B);
  static const Color lovedOneCardLabel = Color(0xFF1E293B);
  static const Color lovedOneRequiredAsterisk = Color(0xFFDC2626);
  static const Color lovedOneInputBg = Color(0xFFFFF2F6);
  static const Color lovedOneInputBorder = Color(0xFFE5E7EB);
  static const Color lovedOneInputPlaceholder = Color(0xFF9CA3AF);
  static const Color lovedOneSectionCardBg = Color(0xFFF8F8F8);
  static const Color lovedOneTileBg = Color(0xFFFFFFFF);
  static const Color lovedOneTileBorder = Color(0xFFE5E7EB);
  static const Color lovedOneTileText = Color(0xFF374151);
  static const Color lovedOneTileSelectedBg = Color(0xFFFFF2F6);
  static const Color lovedOneTileSelectedBorder = Color(0xFFFB7185);

  // --- Individual Step 3 (Your relationship goals) ---
  static const Color goalsBgTop = Color(0xFFFDF5F8);
  static const Color goalsBgBottom = Color(0xFFFAFAFA);
  static const Color goalsBackBtnBg = Color(0xFFFFFFFF);
  static const Color goalsBackBtnIcon = Color(0xFF374151);
  static const Color goalsTargetCircleBg = Color(0xFFBE185D);
  static const Color goalsTargetIcon = Color(0xFFFFFFFF);
  static const Color goalsTitle = Color(0xFF1E293B);
  static const Color goalsDescription = Color(0xFF6B7280);
  static const Color goalsSectionLabel = Color(0xFF1E293B);
  static const Color goalsCardBg = Color(0xFFFFFFFF);
  static const Color goalsCardTitle = Color(0xFF1E293B);
  static const Color goalsCardSubtitle = Color(0xFF6B7280);
  static const Color goalsSaveDisabledBg = Color(0xFFE5E7EB);
  static const Color goalsSaveDisabledText = Color(0xFF9CA3AF);
  static const Color goalsSaveEnabledText = Color(0xFFFFFFFF);
  static const Color goalsFooterText = Color(0xFF9CA3AF);
  static const Color goalsCardIconBgPink = Color(0xFFFFE4EC);
  static const Color goalsCardIconPink = Color(0xFFFB7185);
  static const Color goalsCardIconBgOrange = Color(0xFFFFEDD5);
  static const Color goalsCardIconOrange = Color(0xFFF97316);
  static const Color goalsCardIconBgBlue = Color(0xFFDBEAFE);
  static const Color goalsCardIconBlue = Color(0xFF3B82F6);
  static const Color goalsCardIconBgPurple = Color(0xFFE9D5FF);
  static const Color goalsCardIconPurple = Color(0xFFA855F7);
  static const Color goalsCardIconBgYellow = Color(0xFFFEF3C7);
  static const Color goalsCardIconYellow = Color(0xFFF59E0B);
  static const Color goalsCardIconBgRed = Color(0xFFFEE2E2);
  static const Color goalsCardIconRed = Color(0xFFEF4444);

  // --- Individual Step 4 (Secondary Relationship Goals) ---
  static const Color secGoalsBgTop = Color(0xFFFFFFFF);
  static const Color secGoalsBgBottom = Color(0xFFFDF2F8);
  static const Color secGoalsBackBtnBg = Color(0xFFF9FAFB);
  static const Color secGoalsBackBtnIcon = Color(0xFFA855F7);
  static const Color secGoalsTitle = Color(0xFF1E293B);
  static const Color secGoalsSubtitle = Color(0xFFE11D48);
  static const Color secGoalsDescription = Color(0xFF6B7280);
  static const Color secGoalsPillBg = Color(0xFFFFFFFF);
  static const Color secGoalsPillBorder = Color(0xFFFBCFE8);
  static const Color secGoalsPillText = Color(0xFF1E293B);
  static const Color secGoalsSectionBubbleBeige = Color(0xFFFEF3C7);
  static const Color secGoalsSectionBubbleBlue = Color(0xFFDBEAFE);
  static const Color secGoalsSectionBubblePink = Color(0xFFFFE4EC);
  static const Color secGoalsSectionBubbleYellow = Color(0xFFFEF9C3);
  static const Color secGoalsSectionTitle = Color(0xFF1E293B);
  static const Color secGoalsOptionCardBg = Color(0xFFFFFFFF);
  static const Color secGoalsOptionCardBorder = Color(0xFFFBCFE8);
  static const Color secGoalsOptionText = Color(0xFF6B7280);
  static const Color secGoalsSelectorBorder = Color(0xFFD1D5DB);
  static const Color secGoalsSelectorSelected = Color(0xFFFB7185);
  static const Color secGoalsCtaDisabledBg = Color(0xFFE5E7EB);
  static const Color secGoalsCtaDisabledText = Color(0xFF9CA3AF);
  static const Color secGoalsSkipLink = Color(0xFFA855F7);

  // --- Loved One Preferences ---
  static const Color prefsBgTop = Color(0xFFFDF5F8);
  static const Color prefsBgBottom = Color(0xFFF5F3FF);
  static const Color prefsBackBtnBg = Color(0xFFF3E8FF);
  static const Color prefsBackBtnIcon = Color(0xFFA855F7);
  static const Color prefsProgressInactive = Color(0xFFE9D5FF);
  static const Color prefsProgressActive = Color(0xFFA855F7);
  static const Color prefsOptionalPillBg = Color(0xFFF3E8FF);
  static const Color prefsOptionalPillText = Color(0xFF7C3AED);
  static const Color prefsTitle = Color(0xFF1E293B);
  static const Color prefsSubtitle = Color(0xFF6B7280);
  static const Color prefsSectionBubbleBg = Color(0xFFF5F3FF);
  static const Color prefsSectionTitle = Color(0xFF1E293B);
  static const Color prefsSectionDesc = Color(0xFF6B7280);
  static const Color prefsAddButtonBorder = Color(0xFFF9A8D4);
  static const Color prefsAddButtonText = Color(0xFFEC4899);
  static const Color prefsChipBg = Color(0xFFFFFFFF);
  static const Color prefsChipBorder = Color(0xFFE5E7EB);
  static const Color prefsChipText = Color(0xFF374151);
  static const Color prefsChipSelectedBg = Color(0xFFFFF2F6);
  static const Color prefsChipSelectedBorder = Color(0xFFFB7185);
  static const Color prefsCategoryCardCreative = Color(0xFFFDF2F8);
  static const Color prefsCategoryCardFood = Color(0xFFFEFCE8);
  static const Color prefsCategoryCardExperiences = Color(0xFFECFDF5);
  static const Color prefsCategoryCardWellness = Color(0xFFDCFCE7);
  static const Color prefsCategoryCardFun = Color(0xFFF3E8FF);
  static const Color prefsCategoryCardAmbition = Color(0xFFEFF6FF);
  static const Color prefsCategoryCardRelationships = Color(0xFFFFF2F6);
  static const Color prefsCategoryCardTech = Color(0xFFF9FAFB);
  /// Prefs modal dialogs (Add Special Occasion / Add Custom Hobby)
  static const Color prefsDialogBarrier = Color(0x40000000);
  static const Color prefsDialogBg = Color(0xFFFFFFFF);
  static const Color prefsDialogInputBorder = Color(0xFFE5E7EB);
  static const Color prefsDialogPlaceholder = Color(0xFF9CA3AF);
  static const Color prefsDialogCancelBorder = Color(0xFFE5E7EB);
  static const Color prefsDialogCancelText = Color(0xFF374151);

  // --- Dislikes screen ---
  static const Color dislikesBgTop = Color(0xFFFDF8F9);
  static const Color dislikesBgBottom = Color(0xFFFAFAF9);
  static const Color dislikesBackText = Color(0xFFBE185D);
  static const Color dislikesProgressActive = Color(0xFFE11D48);
  static const Color dislikesProgressInactive = Color(0xFFFBCFE8);
  static const Color dislikesFinalPillBg = Color(0xFFFFF1F2);
  static const Color dislikesFinalPillBorder = Color(0xFFFECDD3);
  static const Color dislikesFinalPillText = Color(0xFFE11D48);
  static const Color dislikesTitle = Color(0xFFC2410C);
  static const Color dislikesDesc = Color(0xFF1E293B);
  static const Color dislikesOptional = Color(0xFFA855F7);
  static const Color dislikesCardGift = Color(0xFFFFF7ED);
  static const Color dislikesCardFood = Color(0xFFFFFBEB);
  static const Color dislikesCardExperiences = Color(0xFFFEF3C7);
  static const Color dislikesCardWellness = Color(0xFFF1F5F9);
  static const Color dislikesCategoryTitle = Color(0xFF1E293B);
  static const Color dislikesChipBg = Color(0xFFFAFAFA);
  static const Color dislikesChipBorder = Color(0xFFE5E7EB);
  static const Color dislikesChipText = Color(0xFF374151);
  static const Color dislikesChipSelectedBg = Color(0xFFFFF2F6);
  static const Color dislikesChipSelectedBorder = Color(0xFFFB7185);
  static const Color dislikesAddButtonBg = Color(0xFFFFFFFF);
  static const Color dislikesAddButtonBorder = Color(0xFFE5E7EB);
  static const Color dislikesAddButtonText = Color(0xFF374151);
  static const Color dislikesHelperText = Color(0xFF9CA3AF);

  // --- Personal Note (Add a Personal Note) ---
  static const Color noteBgTop = Color(0xFFFDF5F8);
  static const Color noteBgBottom = Color(0xFFFFFFFF);
  static const Color noteBackText = Color(0xFFBE185D);
  static const Color noteSkipText = Color(0xFF6B7280);
  static const Color noteLogoHeartBg = Color(0xFFEC4899);
  static const Color noteLogoText = Color(0xFFBE185D);
  static const Color noteUnderline = Color(0xFFF472B6);
  static const Color noteProgressBg = Color(0xFFFBCFE8);
  static const Color noteProgressFill = Color(0xFFE11D48);
  static const Color noteStepLabel = Color(0xFF6B7280);
  static const Color noteBubbleBg = Color(0xFFF3E8FF);
  static const Color noteTitle = Color(0xFF1E293B);
  static const Color noteSubtitle = Color(0xFF374151);
  static const Color noteCardBg = Color(0xFFFFFFFF);
  static const Color noteLabelText = Color(0xFF1E293B);
  static const Color noteRequiredAsterisk = Color(0xFFDC2626);
  static const Color noteThumbsUpIcon = Color(0xFFF59E0B);
  static const Color noteInputBorder = Color(0xFFE5E7EB);
  static const Color noteInputPlaceholder = Color(0xFF9CA3AF);
  static const Color noteCounter = Color(0xFF9CA3AF);
  static const Color noteHelperBoxBg = Color(0xFFF5F3FF);
  static const Color noteHelperText = Color(0xFF374151);
  static const Color noteSeeMoreText = Color(0xFFBE185D);
  static const Color noteSeeMoreIcon = Color(0xFFE11D48);
  static const Color noteCtaDisabledBg = Color(0xFFE5E7EB);
  static const Color noteCtaText = Color(0xFFFFFFFF);

  // --- Subscription (Choose your plan) ---
  static const Color subPageBgTop = Color(0xFFFDF5F8);
  static const Color subPageBgBottom = Color(0xFFFFFFFF);
  static const Color subBackText = Color(0xFFBE185D);
  static const Color subTitle = Color(0xFFBE185D);
  static const Color subSubtitle = Color(0xFF374151);
  static const Color subActiveCardBg = Color(0xFFFFF1F2);
  static const Color subActiveCardBorder = Color(0xFFFECDD3);
  static const Color subActiveLabel = Color(0xFFFB7185);
  static const Color subActiveGreenDot = Color(0xFF22C55E);
  static const Color subActivePlanName = Color(0xFFBE185D);
  static const Color subActiveRenewal = Color(0xFF6B7280);
  static const Color subCurrentBadgeBg = Color(0xFFFFF1F2);
  static const Color subCurrentBadgeText = Color(0xFFBE185D);
  static const Color subCancelLink = Color(0xFFEC4899);
  static const Color subCardBg = Color(0xFFFFFFFF);
  static const Color subCardBorder = Color(0xFFFBCFE8);
  static const Color subPlanName = Color(0xFFBE185D);
  static const Color subPlanSubtitle = Color(0xFF6B7280);
  static const Color subPriceMain = Color(0xFFBE185D);
  static const Color subPricePeriod = Color(0xFF6B7280);
  static const Color subSectionLabel = Color(0xFFFB7185);
  static const Color subIncludeText = Color(0xFF374151);
  static const Color subIncludeDetail = Color(0xFF9CA3AF);
  static const Color subBestFor = Color(0xFF6B7280);
  static const Color subCtaText = Color(0xFFFFFFFF);
  static const Color subRecPillText = Color(0xFFFFFFFF);

  // --- Checkout (Complete Your Order) ---
  static const Color checkoutPageBgTop = Color(0xFFFDF5F8);
  static const Color checkoutPageBgBottom = Color(0xFFFFFFFF);
  static const Color checkoutBackText = Color(0xFFBE185D);
  static const Color checkoutSecureBg = Color(0xFFD1FAE5);
  static const Color checkoutSecureBorder = Color(0xFF6EE7B7);
  static const Color checkoutSecureText = Color(0xFF047857);
  static const Color checkoutSecureIcon = Color(0xFF059669);
  static const Color checkoutTitle = Color(0xFF1E293B);
  static const Color checkoutSubtitle = Color(0xFF6B7280);
  static const Color checkoutCardBg = Color(0xFFFFFFFF);
  static const Color checkoutCardBorder = Color(0xFFFBCFE8);
  static const Color checkoutSectionTitle = Color(0xFF1E293B);
  static const Color checkoutIconSquarePink = Color(0xFFFB7185);
  static const Color checkoutIconSquarePurple = Color(0xFFA855F7);
  static const Color checkoutInputBg = Color(0xFFF9FAFB);
  static const Color checkoutInputBorder = Color(0xFFE5E7EB);
  static const Color checkoutInputPlaceholder = Color(0xFF9CA3AF);
  static const Color checkoutPaymentTileBorder = Color(0xFFFBCFE8);
  static const Color checkoutPaymentTileSelectedBg = Color(0xFFFFF1F2);
  static const Color checkoutPaymentTileSelectedBorder = Color(0xFFFB7185);
  static const Color checkoutPaymentTileSelectedText = Color(0xFFBE185D);
  static const Color checkoutPaymentTileDot = Color(0xFFEC4899);
  static const Color checkoutPaymentTileUnselectedText = Color(0xFF374151);
  static const Color checkoutSecurityBoxBg = Color(0xFFECFDF5);
  static const Color checkoutSecurityBoxBorder = Color(0xFFA7F3D0);
  static const Color checkoutSecurityBoxTitle = Color(0xFF065F46);
  static const Color checkoutSecurityBoxDesc = Color(0xFF047857);
  static const Color checkoutOrderPlanName = Color(0xFF1E293B);
  static const Color checkoutOrderPricePeriod = Color(0xFF6B7280);
  static const Color checkoutDueTodayLabel = Color(0xFF1E293B);
  static const Color checkoutDisclaimerBg = Color(0xFFF3F4F6);
  static const Color checkoutDisclaimerText = Color(0xFF6B7280);
  static const Color checkoutCtaText = Color(0xFFFFFFFF);
  static const Color checkoutFooterCheck = Color(0xFF059669);
  static const Color checkoutFooterText = Color(0xFF374151);

  // --- Home (Individual Home Dashboard) ---
  static const Color homePageBgStart = Color(0xFFFFF1F2); // rose-50
  static const Color homePageBgMid = Color(0xFFFDF2F8); // pink-50
  static const Color homePageBgEnd = Color(0xFFFAF5FF); // purple-50
  static const Color homeTopBarBg = Color(0xF2FFF1F2); // rose-50/95
  static const Color homeHeartIconBg = Color(0xFFE9D5FF); // light purple circle
  static const Color homeIconButtonBg = Color(0xCCFFFFFF); // white/80
  static const Color homeIconButtonBorder = Color(0x80FBCFE8); // pink-200/50
  static const Color homeBellIcon = Color(0xFFE11D48); // rose-600
  static const Color homeNotificationDot = Color(0xFFE11D48);
  static const Color homeGreetingCardBg = Color(0xCCFFFFFF);
  static const Color homeGreetingCardBorder = Color(0x80FBCFE8);
  static const Color homeGreetingTitle = Color(0xFF1F2937); // gray-800
  static const Color homeGreetingSubtitle = Color(0xFF4B5563); // gray-600
  static const Color homePillRoseBg = Color(0xFFFFF1F2);
  static const Color homePillRoseBorder = Color(0x4DFECDD3); // rose-200/30
  static const Color homePillPurpleBg = Color(0xFFFAF5FF);
  static const Color homePillPurpleBorder = Color(0x4DE9D5FF); // purple-200/30
  static const Color homePillText = Color(0xFF374151); // gray-700
  static const Color homeSectionTitle = Color(0xFF1F2937);
  static const Color homeSectionSubtitle = Color(0xFF4B5563);
  static const Color homeSwipeHint = Color(0xFFA855F7); // purple-500
  static const Color homeMessageCardBorder = Color(0xFFFBCFE8); // rose-300
  static const Color homeMessageCardBg = Color(0xFFFFFFFF);
  static const Color homeMessageBubbleBgStart = Color(0xFFFFF1F2);
  static const Color homeMessageBubbleBgEnd = Color(0xFFFDF2F8);
  static const Color homeMessageBubbleBorder = Color(0xFFFBCFE8);
  static const Color homePrevNextBg = Color(0xFFFFFFFF);
  static const Color homePrevNextBorder = Color(0xFFFBCFE8);
  static const Color homePrevNextText = Color(0xFFE11D48);
  static const Color homeRegenerateGradientStart = Color(0xFFE11D48); // rose-500
  static const Color homeRegenerateGradientMid = Color(0xFFEC4899); // pink-500
  static const Color homeRegenerateGradientEnd = Color(0xFFA855F7); // purple-500
  static const Color homeEventCardBorderUrgent = Color(0xFFFBCFE8);
  static const Color homeEventCardBorder = Color(0x80FBCFE8);
  static const Color homeUrgentBadgeStart = Color(0xFFE11D48);
  static const Color homeUrgentBadgeEnd = Color(0xFFEC4899);
  static const Color homeEventDaysText = Color(0xFFE11D48);
  static const Color homeInspirationCardBgStart = Color(0xFFFAF5FF);
  static const Color homeInspirationCardBgMid = Color(0xFFFDF2F8);
  static const Color homeInspirationCardBgEnd = Color(0xFFFFF1F2);
  static const Color homeInspirationCardBorder = Color(0x80E9D5FF);
  static const Color homeInspirationQuoteBg = Color(0xCCFFFFFF);
  static const Color homeInspirationLikeInactive = Color(0xFF374151);
  static const Color homeInspirationLikeActiveBgStart = Color(0xFFE11D48);
  static const Color homeInspirationLikeActiveBgEnd = Color(0xFFEC4899);
  static const Color homeBottomNavBg = Color(0xE6FFFFFF);
  static const Color homeBottomNavBorder = Color(0x80FECDD3);
  static const Color homeBottomNavActivePillStart = Color(0xFFFECDD3);
  static const Color homeBottomNavActivePillMid = Color(0xFFFBCFE8);
  static const Color homeBottomNavActivePillEnd = Color(0xFFFFF1F2);
  static const Color homeBottomNavActiveIcon = Color(0xFFE11D48);
  static const Color homeBottomNavActiveText = Color(0xFF1F2937);
  static const Color homeBottomNavInactiveIcon = Color(0xFF9CA3AF);
  static const Color homeBottomNavInactiveText = Color(0xFF4B5563);
  static const Color homeLikeGreenBg = Color(0xFFECFDF5);
  static const Color homeLikeGreenBorder = Color(0xFFA7F3D0);
  static const Color homeLikeGreenText = Color(0xFF047857);
  static const Color homeDislikeRedBg = Color(0xFFFEF2F2);
  static const Color homeDislikeRedBorder = Color(0xFFFECACA);
  static const Color homeDislikeRedText = Color(0xFFB91C1C);

  // --- Notifications list ---
  static const Color notifPageBgStart = Color(0xFFFFF1F2);
  static const Color notifPageBgMid = Color(0xFFFDF2F8);
  static const Color notifPageBgEnd = Color(0xFFFAF5FF);
  static const Color notifHeaderBg = Color(0xF2FFF1F2);
  static const Color notifHeaderBorder = Color(0x80FBCFE8);
  static const Color notifBackText = Color(0xFFE11D48);
  static const Color notifMarkAllReadStart = Color(0xFFE91E63);
  static const Color notifMarkAllReadEnd = Color(0xFFF06292);
  static const Color notifBellIconStart = Color(0xFFE91E63);
  static const Color notifBellIconEnd = Color(0xFFF06292);
  static const Color notifTitleGradientStart = Color(0xFFE11D48);
  static const Color notifTitleGradientMid = Color(0xFFEC4899);
  static const Color notifTitleGradientEnd = Color(0xFFA855F7);
  static const Color notifSubtitle = Color(0xFF4B5563);
  static const Color notifTabActiveText = Color(0xFFFFFFFF);
  static const Color notifTabInactiveText = Color(0xFF6B4B5E);
  static const Color notifTabInactiveBg = Color(0xFFFFFFFF);
  static const Color notifTabInactiveBorder = Color(0x33F6A6C1);
  static const Color notifCardBg = Color(0xCCFFFFFF);
  static const Color notifCardBorderRead = Color(0x1AF6A6C1);
  static const Color notifCardBorderUnread = Color(0x4DE91E63);
  static const Color notifCardTitle = Color(0xFF1F2937);
  static const Color notifCardTime = Color(0xFF6B7280);
  static const Color notifCardBody = Color(0xFF4B5563);
  static const Color notifTagPillBgStart = Color(0xFFFFF5F8);
  static const Color notifTagPillBgEnd = Color(0xFFFFE4EC);
  static const Color notifTagPillText = Color(0xFFE91E63);
  static const Color notifTagPillBorder = Color(0x33E91E63);
  static const Color notifMarkReadBtnStart = Color(0xFFE91E63);
  static const Color notifMarkReadBtnEnd = Color(0xFFF06292);
  static const Color notifDeleteBtnBg = Color(0xFFFFFFFF);
  static const Color notifDeleteBtnBorder = Color(0x33F6A6C1);
  static const Color notifDeleteBtnText = Color(0xFF6B4B5E);
  static const Color notifUnreadBarStart = Color(0xFFE91E63);
  static const Color notifUnreadBarEnd = Color(0xFFF06292);
  static const Color notifEmptyIconBgStart = Color(0xFFF6A6C1);
  static const Color notifEmptyIconBgEnd = Color(0xFFFAD0DC);
  static const Color notifEmptyTitle = Color(0xFF1F2937);
  static const Color notifEmptyBody = Color(0xFF4B5563);

  // --- Profile (User Profile view/edit) ---
  static const Color profileHeaderStart = Color(0xFFF43F5E); // rose-400
  static const Color profileHeaderMid = Color(0xFFF472B6);  // pink-400
  static const Color profileHeaderEnd = Color(0xFFA78BFA);  // purple-400
  static const Color profileTitleText = Color(0xFFFFFFFF);
  static const Color profileEditBtnBg = Color(0xFFFFFFFF);
  static const Color profileEditBtnBorder = Color(0xFFFB7185); // thin red/pink border view mode
  static const Color profileEditBtnIcon = Color(0xFFE11D48);
  static const Color profileEditBtnActiveStart = Color(0xFFE11D48);
  static const Color profileEditBtnActiveEnd = Color(0xFFEC4899);
  static const Color profileAvatarBorder = Color(0xFFFFFFFF);
  static const Color profileStatusDot = Color(0xFF4ADE80);  // green-400
  static const Color profileUsernameText = Color(0xFFFFFFFF);
  static const Color profileMembershipText = Color(0xE6FFFFFF);
  static const Color profileMembershipDot = Color(0xFFFDE047); // yellow-300
  static const Color profileCardBg = Color(0xCCFFFFFF);
  static const Color profileCardBgGradientStart = Color(0x80FFE4E6); // rose-100/50
  static const Color profileCardBgGradientEnd = Color(0x80FCE7F3);   // pink-100/50
  static const Color profileStatLabel = Color(0xFF4B5563);
  static const Color profileStatCount = Color(0xFF1F2937);
  static const Color profileStatDelta = Color(0xFF16A34A);   // green-600
  static const Color profileStatIconRose = Color(0xFFFB7185);
  static const Color profileStatIconPink = Color(0xFFF472B6);
  static const Color profileStatIconPurple = Color(0xFFA78BFA);
  /// Stat card top-right decorative circle (React: bg-rose-100, bg-pink-100, bg-purple-100)
  static const Color profileStatDecoRose = Color(0xFFFFE4E6);
  static const Color profileStatDecoPink = Color(0xFFFCE7F3);
  static const Color profileStatDecoPurple = Color(0xFFF3E8FF);
  static const Color profileInfoTitle = Color(0xFF1F2937);
  static const Color profileInfoLabel = Color(0xFF6B7280);
  static const Color profileInfoValue = Color(0xFF1F2937);
  static const Color profileInfoIconBg = Color(0xFFFFF1F2);
  static const Color profileInputBorder = Color(0xFFE5E7EB);
  static const Color profileInputBg = Color(0xFFF9FAFB);
  static const Color profileInputPlaceholder = Color(0xFF9CA3AF);
  static const Color profileSaveBtnStart = Color(0xFFE11D48);
  static const Color profileSaveBtnMid = Color(0xFFEC4899);
  static const Color profileSaveBtnEnd = Color(0xFFA855F7);
  static const Color profileManageSubBgStart = Color(0xFFF5F3FF);
  static const Color profileManageSubBgEnd = Color(0xFFFAF5FF);
  static const Color profileManageSubBorder = Color(0xFFD8B4FE);
  static const Color profileManageSubText = Color(0xFF9333EA);
  static const Color profileLogoutBgStart = Color(0xFFFFF5F8);
  static const Color profileLogoutBgEnd = Color(0xFFFFE8F0);
  static const Color profileLogoutBorder = Color(0xFFF6A6C1);
  static const Color profileLogoutText = Color(0xFFD84B7A);
  static const Color profileLogoutBtnBg = Color(0xFFFFFFFF); // white bg per design
  // --- Search (Individual Search screen) ---
  static const Color searchHeaderStart = Color(0xFFA78BFA);   // purple-400
  static const Color searchHeaderMid = Color(0xFF8B5CF6);     // purple-500
  static const Color searchHeaderEnd = Color(0xFF6366F1);     // indigo-500
  static const Color searchTitleText = Color(0xFFFFFFFF);
  static const Color searchBarBg = Color(0xFFFFFFFF);
  static const Color searchBarIcon = Color(0xFFA78BFA);       // purple-400
  static const Color searchBarPlaceholder = Color(0xFF9CA3AF); // gray-400
  static const Color searchBarText = Color(0xFF1F2937);      // gray-800
  static const Color searchPageBgTop = Color(0x4DFAF5FF);    // purple-50/30
  static const Color searchPageBgEnd = Color(0xFFFFFFFF);
  static const Color searchSectionTitle = Color(0xFF374151);  // gray-700
  static const Color searchQuickTileLovedOnesStart = Color(0xFFFB7185);   // rose-400
  static const Color searchQuickTileLovedOnesEnd = Color(0xFFF472B6);    // pink-400
  static const Color searchQuickTileGiftStart = Color(0xFFA78BFA);        // purple-400
  static const Color searchQuickTileGiftEnd = Color(0xFF818CF8);         // indigo-400
  static const Color searchQuickTileEventsStart = Color(0xFF60A5FA);      // blue-400
  static const Color searchQuickTileEventsEnd = Color(0xFF22D3EE);       // cyan-400
  static const Color searchQuickTileMessagesStart = Color(0xFFF472B6);    // pink-400
  static const Color searchQuickTileMessagesEnd = Color(0xFFFB7185);      // rose-400
  static const Color searchQuickTileIcon = Color(0xFFFFFFFF);
  static const Color searchQuickTileLabel = Color(0xFFFFFFFF);
  static const Color searchTrendingBubbleStart = Color(0xFFF3E8FF);       // purple-100
  static const Color searchTrendingBubbleEnd = Color(0xFFFCE7F3);         // pink-100
  static const Color searchTrendingTitle = Color(0xFF1F2937);            // gray-800
  static const Color searchTrendingSubtitle = Color(0xFF9CA3AF);         // gray-400
  static const Color searchTrendingArrow = Color(0xFFD8B4FE);           // purple-300
  static const Color searchRecentChipBg = Color(0xFFFFFFFF);
  static const Color searchRecentChipBorder = Color(0xFFF3E8FF);         // purple-100
  static const Color searchRecentChipText = Color(0xFF374151);          // gray-700
  // --- Loved Ones list screen ---
  static const Color lovedOnesPageBgStart = Color(0xFFFFF1F2);         // rose-50
  static const Color lovedOnesPageBgMid = Color(0xFFFDF2F8);           // pink-50
  static const Color lovedOnesPageBgEnd = Color(0xFFFAF5FF);           // purple-50
  static const Color lovedOnesHeaderBg = Color(0xF2FFF1F2);             // rose-50/95
  static const Color lovedOnesBackBtnBg = Color(0xCCFFFFFF);            // white/80
  static const Color lovedOnesBackBtnBorder = Color(0x80FECDD3);        // pink-200/50
  static const Color lovedOnesBackIcon = Color(0xFFE11D48);             // rose-600
  static const Color lovedOnesTitle = Color(0xFF1F2937);               // gray-800
  static const Color lovedOnesSubtitle = Color(0xFF4B5563);            // gray-600
  static const Color lovedOnesAddLabel = Color(0xFF6B7280);            // gray-500
  static const Color lovedOnesCardBg = Color(0xE6FFFFFF);               // white/90
  static const Color lovedOnesCardBorder = Color(0xFFFECDD3);          // rose-200
  static const Color lovedOnesAvatarBgStart = Color(0xFFFFE4E6);       // rose-100
  static const Color lovedOnesAvatarBgEnd = Color(0xFFFCE7F3);         // pink-100
  static const Color lovedOnesAvatarRing = Color(0xFFFECDD3);          // rose-200
  static const Color lovedOnesName = Color(0xFF1F2937);                 // gray-800
  static const Color lovedOnesRelationship = Color(0xFF4B5563);        // gray-600
  static const Color lovedOnesEditBtnBg = Color(0xFFFFF1F2);            // rose-50
  static const Color lovedOnesEditBtnBorder = Color(0xFFFECDD3);       // rose-200
  static const Color lovedOnesEditIcon = Color(0xFFE11D48);             // rose-600
  static const Color lovedOnesDeleteBtnBg = Color(0xFFFEF2F2);          // red-50
  static const Color lovedOnesDeleteBtnBorder = Color(0xFFFECACA);     // red-200
  static const Color lovedOnesDeleteIcon = Color(0xFFDC2626);           // red-600
  // --- Account Settings modal ---
  static const Color accountSettingsBarrier = Color(0x80000000);       // black/50
  static const Color accountSettingsDialogBg = Color(0xFFFFFFFF);
  static const Color accountSettingsTitle = Color(0xFFFFFFFF);
  static const Color accountSettingsSubtitle = Color(0xCCFFFFFF);        // white/80
  static const Color accountSettingsCloseBtnBg = Color(0x33FFFFFF);      // white/20
  static const Color accountSettingsRowTitle = Color(0xFF1F2937);      // gray-800
  static const Color accountSettingsRowSubtitle = Color(0xFF6B7280);   // gray-500
  static const Color accountSettingsChevronPurple = Color(0xFFA78BFA);  // purple-400
  static const Color accountSettingsChevronBlue = Color(0xFF60A5FA);    // blue-400
  static const Color accountSettingsChevronGreen = Color(0xFF34D399);   // emerald-400
  static const Color accountSettingsChevronGray = Color(0xFF9CA3AF);   // gray-400
  // --- Manage Subscription screen ---
  static const Color manageSubPageBg = Color(0xFFFFF7F8);             // very light pink
  static const Color manageSubAppBarTitle = Color(0xFF333333);         // dark gray
  static const Color manageSubBackIcon = Color(0xFFEC407A);             // rose/pink
  static const Color manageSubHelpBtnBg = Color(0xFFE5E5E5);          // light gray circle
  static const Color manageSubHelpBtnBorder = Color(0xFFC8C8C8);
  static const Color manageSubHelpIcon = Color(0xFF666666);
  static const Color manageSubCurrentPlanLabel = Color(0xFF888888);     // medium gray
  static const Color manageSubCrownBubbleBg = Color(0xFFE0BBE4);       // light purple
  static const Color manageSubPlanName = Color(0xFF333333);
  static const Color manageSubUpgradeBtnBg = Color(0xFFF06292);        // bright pink
  static const Color manageSubUpgradeBtnText = Color(0xFFFFFFFF);
  static const Color manageSubUnsubscribeLink = Color(0xFFEC407A);     // medium pink
  static const Color manageSubCardBg = Color(0xFFFFFFFF);
  static const Color manageSubCardShadow = Color(0x1A000000);
  static const Color manageSubChooseTitle = Color(0xFF333333);
  static const Color manageSubChooseSubtitle = Color(0xFF888888);
  static const Color manageSubPlanCardBorderEssential = Color(0xFFFBCFE8);  // faint pink
  static const Color manageSubPlanCardBorderPlus = Color(0xFFE9D5FF);       // faint purple
  static const Color manageSubPlanCardBorderUnlimited = Color(0xFFC4B5FD);  // faint blue-purple
  static const Color manageSubBadgeCurrentBg = Color(0xFF22C55E);      // green
  static const Color manageSubBadgeCurrentText = Color(0xFFFFFFFF);
  static const Color manageSubBadgePopularBg = Color(0xFFA855F7);      // purple
  static const Color manageSubBadgePopularText = Color(0xFFFFFFFF);
  static const Color manageSubCtaDisabledBg = Color(0xFFE5E7EB);       // light gray
  static const Color manageSubCtaDisabledText = Color(0xFF6B7280);
  static const Color manageSubUpgradeGradientStart = Color(0xFF6366F1);    // indigo
  static const Color manageSubUpgradeGradientEnd = Color(0xFFA855F7);       // purple
  static const Color manageSubDowngradeGradientStart = Color(0xFF374151);   // gray-700
  static const Color manageSubDowngradeGradientEnd = Color(0xFF111827);     // gray-900
  // --- Before you go dialog ---
  static const Color beforeYouGoBarrier = Color(0x80000000);           // black/50
  static const Color beforeYouGoDialogBg = Color(0xFFFFFFFF);
  static const Color beforeYouGoIconBubbleBg = Color(0xFFE9D5FF);       // light purple
  static const Color beforeYouGoIconBubbleIcon = Color(0xFF7C3AED);     // purple-600
  static const Color beforeYouGoTitle = Color(0xFF1F2937);             // gray-800
  static const Color beforeYouGoSubtitle = Color(0xFF6B7280);           // gray-500
  static const Color beforeYouGoCardPauseBg = Color(0xFFEFF6FF);        // light blue
  static const Color beforeYouGoCardPauseBorder = Color(0xFFBFDBFE);  // blue-200
  static const Color beforeYouGoCardPauseIconBg = Color(0xFF3B82F6);    // blue-500
  static const Color beforeYouGoCardLowerBg = Color(0xFFFDF2F8);       // light pink
  static const Color beforeYouGoCardLowerBorder = Color(0xFFFBCFE8);   // pink-200
  static const Color beforeYouGoCardLowerIconBg = Color(0xFFA855F7);    // purple-500
  static const Color beforeYouGoCancelBtnBg = Color(0xFFF3F4F6);       // gray-100
  static const Color beforeYouGoCancelBtnText = Color(0xFF374151);      // gray-700
  static const Color beforeYouGoKeepLinkText = Color(0xFF6B7280);       // gray-500
  // --- Business cancel flow (Why are you leaving? / Final Step) ---
  static const Color businessCancelIconBubbleWhy = Color(0xFFFFE4E6);  // rose-100
  static const Color businessCancelIconWhy = Color(0xFFF43F5E);       // rose-500
  static const Color businessCancelIconBubbleFinal = Color(0xFFFEE2E2); // red-100
  static const Color businessCancelIconFinal = Color(0xFFEF4444);     // red-500
  static const Color businessCancelLoseAccessBoxStart = Color(0xFFFFF1F2); // rose-50
  static const Color businessCancelLoseAccessBoxEnd = Color(0xFFFDF2F8); // pink-50
  static const Color businessCancelLoseAccessBorder = Color(0x80FECDD3);  // rose-200/50
  static const Color businessCancelLoseAccessTitle = Color(0xFF1F2937);
  static const Color businessCancelLoseAccessItem = Color(0xFF4B5563);
  static const Color businessCancelLoseAccessX = Color(0xFFF43F5E);   // rose-500
  static const Color businessCancelReasonTileBg = Color(0xFFFFF1F2);  // rose-50
  static const Color businessCancelReasonTileBorder = Color(0xFFFECDD3); // rose-200
  static const Color businessCancelReasonTileSelectedBg = Color(0xFFFAF5FF); // purple-50
  static const Color businessCancelReasonTileSelectedBorder = Color(0xFFC084FC); // purple-400
  static const Color businessCancelReasonCheckSelected = Color(0xFF9333EA); // purple-600
  static const Color businessCancelReasonCheckUnselected = Color(0xFFD1D5DB); // gray-300
  static const Color businessCancelContinueDisabledBg = Color(0xFFF3F4F6);
  static const Color businessCancelContinueDisabledText = Color(0xFF9CA3AF); // gray-400
  static const Color businessCancelKeepOutlinedBorder = Color(0xFFE5E7EB); // gray-200
  static const Color businessCancelFeedbackBorder = Color(0xFFE5E7EB);
  static const Color businessCancelFeedbackLabel = Color(0xFF374151);
  static const Color businessCancelFeedbackPlaceholder = Color(0xFF9CA3AF);
  static const Color businessCancelConfirmBtnStart = Color(0xFF6B7280);   // gray-500
  static const Color businessCancelConfirmBtnEnd = Color(0xFF4B5563);    // gray-600
  // --- Help & Feedback ---
  static const Color helpFeedbackPageBgTop = Color(0xFFFFFFFF);
  static const Color helpFeedbackPageBgEnd = Color(0xFFFDF2F8);        // light pink-purple
  static const Color helpFeedbackBackBtnBg = Color(0xFFF3F4F6);
  static const Color helpFeedbackBackIcon = Color(0xFFA855F7);
  static const Color helpFeedbackTitle = Color(0xFF1F2937);
  static const Color helpFeedbackSubtitle = Color(0xFF9CA3AF);         // purple-pink tint
  static const Color helpFeedbackCardBg = Color(0xFFFFFFFF);
  static const Color helpFeedbackSectionTitle = Color(0xFF7C3AED);      // medium purple
  static const Color helpFeedbackOptionBorder = Color(0xFFE5E7EB);
  static const Color helpFeedbackOptionText = Color(0xFF374151);
  static const Color helpFeedbackRequiredAsterisk = Color(0xFFDC2626);
  static const Color helpFeedbackPlaceholder = Color(0xFFD1D5DB);       // light purple-pink
  static const Color helpFeedbackCounter = Color(0xFF9CA3AF);
  static const Color helpFeedbackCheckboxLabel = Color(0xFF374151);
  static const Color helpFeedbackSubmitGradientStart = Color(0xFFEC4899);
  static const Color helpFeedbackSubmitGradientEnd = Color(0xFFA855F7);
  static const Color helpFeedbackFooterText = Color(0xFF9CA3AF);
  // --- Gift Ideas screen ---
  static const Color giftIdeasPageBgTop = Color(0xFFFFFFFF);
  static const Color giftIdeasPageBgEnd = Color(0xFFFDF2F8);
  static const Color giftIdeasBackBtnGradientStart = Color(0xFFA78BFA);
  static const Color giftIdeasBackBtnGradientEnd = Color(0xFFEC4899);
  static const Color giftIdeasGreeting = Color(0xFF4B5563);
  static const Color giftIdeasTitle = Color(0xFFBE185D);
  static const Color giftIdeasSubtitle = Color(0xFF4B5563);
  static const Color giftIdeasStatCardBg = Color(0xFFFFFFFF);
  static const Color giftIdeasStatNumber = Color(0xFF1F2937);
  static const Color giftIdeasStatLabel = Color(0xFF4B5563);
  static const Color giftIdeasViewAllBtnStart = Color(0xFFEC4899);
  static const Color giftIdeasViewAllBtnEnd = Color(0xFFA855F7);
  static const Color giftIdeasEventCardBg = Color(0xFFFFFFFF);
  static const Color giftIdeasEventTitle = Color(0xFF1F2937);
  static const Color giftIdeasEventDate = Color(0xFF6B7280);
  static const Color giftIdeasCountdownUrgent = Color(0xFFE11D48);
  static const Color giftIdeasCountdownNormal = Color(0xFF374151);
  static const Color giftIdeasUrgentBadgeBg = Color(0xFFE11D48);
  static const Color giftIdeasUrgentBadgeText = Color(0xFFFFFFFF);
  static const Color giftIdeasViewGiftBtnStart = Color(0xFFEC4899);
  static const Color giftIdeasViewGiftBtnEnd = Color(0xFFA855F7);

  // --- Gift Ideas Detail (event-specific) ---
  static const Color giftIdeasDetailPageBgStart = Color(0xFFFFF1F2);
  static const Color giftIdeasDetailPageBgMid = Color(0xFFFDF2F8);
  static const Color giftIdeasDetailPageBgEnd = Color(0xFFFAF5FF);
  static const Color giftIdeasDetailHeaderBg = Color(0xF2FFF1F2);
  static const Color giftIdeasDetailHeaderBorder = Color(0x80FECDD3);
  static const Color giftIdeasDetailTitle = Color(0xFF1F2937);
  static const Color giftIdeasDetailCardBg = Color(0xCCFFFFFF);
  static const Color giftIdeasDetailCardBorder = Color(0x80FBCFE8);
  static const Color giftIdeasDetailEventTitleGradientStart = Color(0xFFE11D48);
  static const Color giftIdeasDetailEventTitleGradientMid = Color(0xFFEC4899);
  static const Color giftIdeasDetailEventTitleGradientEnd = Color(0xFFA855F7);
  static const Color giftIdeasDetailCountdownDays = Color(0xFFE11D48);
  static const Color giftIdeasDetailFilterLabel = Color(0xFF374151);
  static const Color giftIdeasDetailFilterBorder = Color(0xFFE5E7EB);
  static const Color giftIdeasDetailShowingCount = Color(0xFFE11D48);
  static const Color giftIdeasDetailWhyPerfectBgStart = Color(0xFFFAF5FF);
  static const Color giftIdeasDetailWhyPerfectBgEnd = Color(0xFFFDF2F8);
  static const Color giftIdeasDetailWhyPerfectTitle = Color(0xFF374151);
  static const Color giftIdeasDetailSecondaryBtnBg = Color(0xFFF9FAFB);
  static const Color giftIdeasDetailSecondaryBtnBorder = Color(0xFFE5E7EB);
  static const Color giftIdeasDetailSecondaryBtnText = Color(0xFF374151);
  static const Color giftIdeasDetailSavedBtnBg = Color(0xFFFFF1F2);
  static const Color giftIdeasDetailSavedBtnBorder = Color(0xFFFECDD3);
  static const Color giftIdeasDetailSavedBtnText = Color(0xFFBE185D);
  static const Color giftIdeasDetailTipIcon = Color(0xFF7C3AED);
  static const Color giftIdeasDetailRegenerateDisabledBg = Color(0xFFD1D5DB);
  static const Color giftIdeasDetailRegenerateDisabledText = Color(0xFF9CA3AF);
  static const Color giftIdeasDetailViewHistoryBorder = Color(0x80FBCFE8);
  static const Color giftIdeasDetailViewHistoryCaption = Color(0xFF6B7280);

  // --- All Upcoming Events screen ---
  static const Color eventsPageBg = Color(0xFFFAF5FF);
  static const Color eventsBackText = Color(0xFF7C3AED);
  static const Color eventsHeaderCardBg = Color(0xFFFFFBFE);
  static const Color eventsTitle = Color(0xFF1F2937);
  static const Color eventsSubtitle = Color(0xFF6B7280);
  static const Color eventsSortLabel = Color(0xFF1F2937);
  static const Color eventsSortSelectedText = Color(0xFFFFFFFF);
  static const Color eventsSortUnselectedBg = Color(0xFFF9FAFB);
  static const Color eventsSortUnselectedBorder = Color(0xFFE5E7EB);
  static const Color eventsSortUnselectedText = Color(0xFF1F2937);
  static const Color eventsCardBg = Color(0xFFFFFFFF);
  static const Color eventsUrgentBadgeBg = Color(0xFFDC2626);
  static const Color eventsSpecialBadgeBg = Color(0xFFA855F7);
  static const Color eventsBadgeText = Color(0xFFFFFFFF);
  static const Color eventsRelationship = Color(0xFF6B7280);
  static const Color eventsCountdownPill = Color(0xFF6B7280);
  static const Color eventsStayPreparedCardBg = Color(0xFFFFFBFE);
  static const Color eventsStayPreparedText = Color(0xFF374151);
  // --- Old Messages screen ---
  static const Color oldMessagesPageBg = Color(0xFFFFF1F2);
  static const Color oldMessagesBackIcon = Color(0xFF333333);
  static const Color oldMessagesTitle = Color(0xFF1F2937);
  static const Color oldMessagesChipSelectedStart = Color(0xFFF43F5E);
  static const Color oldMessagesChipSelectedEnd = Color(0xFFA855F7);
  static const Color oldMessagesChipSelectedText = Color(0xFFFFFFFF);
  static const Color oldMessagesChipUnselectedBg = Color(0xFFFFFFFF);
  static const Color oldMessagesChipUnselectedBorder = Color(0xFFFBCFE8);
  static const Color oldMessagesChipUnselectedText = Color(0xFF1F2937);
  static const Color oldMessagesCardBg = Color(0xFFFFFFFF);
  static const Color oldMessagesCardName = Color(0xFF1F2937);
  static const Color oldMessagesCardCount = Color(0xFF6B7280);
  static const Color oldMessagesAvatarBg = Color(0xFFFBCFE8);
  static const Color oldMessagesChevron = Color(0xFF9CA3AF);

  // --- Edit Loved One / Edit Profile ---
  static const Color editLovedOnePageBgStart = Color(0xFFFFF1F2); // rose-50
  static const Color editLovedOnePageBgMid = Color(0xFFFDF2F8);    // pink-50
  static const Color editLovedOnePageBgEnd = Color(0xFFFAF5FF);   // purple-50
  static const Color editLovedOneHeaderBg = Color(0xF2FFF1F2);    // rose-50/95
  static const Color editLovedOneHeaderBorder = Color(0x80FECDD3);  // rose-100/50
  static const Color editLovedOneBackText = Color(0xFFE11D48);     // rose-600
  static const Color editLovedOneTitle = Color(0xFF1F2937);        // gray-800
  static const Color editLovedOneCardBg = Color(0xCCFFFFFF);       // white/80
  static const Color editLovedOneCardBorder = Color(0x80FBCFE8);   // rose-200/50
  static const Color editLovedOneSectionIcon = Color(0xFFE11D48);  // rose-500
  static const Color editLovedOneLabel = Color(0xFF374151);        // gray-700
  static const Color editLovedOneRequiredAsterisk = Color(0xFFE11D48);
  static const Color editLovedOneInputBorder = Color(0xFFFBCFE8);  // pink-200
  static const Color editLovedOneInputFocusBorder = Color(0xFFF9A8D4); // pink-400
  static const Color editLovedOnePlaceholder = Color(0xFF9CA3AF);
  static const Color editLovedOneDashedBtnBorder = Color(0xFFFDA4AF); // rose-300
  static const Color editLovedOneDashedBtnBg = Color(0x80FFF1F2);  // rose-50/50
  static const Color editLovedOneDashedBtnText = Color(0xFFE11D48);
  static const Color editLovedOneInfoCardBgStart = Color(0xFFFAF5FF); // purple-50
  static const Color editLovedOneInfoCardBgEnd = Color(0xFFFDF2F8);   // pink-50
  static const Color editLovedOneInfoCardBorder = Color(0x80E9D5FF);  // purple-200/50
  static const Color editLovedOneInfoCardIcon = Color(0xFFA855F7);
  static const Color editLovedOneInfoCardTitle = Color(0xFF1F2937);
  static const Color editLovedOneInfoCardBody = Color(0xFF4B5563);
  static const Color editLovedOneSecondaryPillBg = Color(0xFFF3E8FF); // purple-100
  static const Color editLovedOneSecondaryPillText = Color(0xFF7C3AED); // purple-700
  static const Color editLovedOneSecondaryRowSelectedBgStart = Color(0xFFFFF1F2);
  static const Color editLovedOneSecondaryRowSelectedBgEnd = Color(0xFFFDF2F8);
  static const Color editLovedOneSecondaryRowSelectedBorder = Color(0xFFF9A8D4);
  static const Color editLovedOneSecondaryRowText = Color(0xFFBE185D); // rose-700
  static const Color editLovedOnePhotoChangeText = Color(0xFF4B5563);
  static const Color editLovedOneCameraBadgeStart = Color(0xFFE11D48);
  static const Color editLovedOneCameraBadgeEnd = Color(0xFFEC4899);
  static const Color editLovedOneDislikesCardBorder = Color(0x80FECACA); // red-200/50
  static const Color editLovedOneDislikesSectionIcon = Color(0xFFDC2626);
  static const Color editLovedOneCustomDislikeChipBg = Color(0xFFFFF1F2);
  static const Color editLovedOneCustomDislikeChipBorder = Color(0xFFFECACA);
  static const Color editLovedOneAddCustomDislikeBg = Color(0x80FEF2F2); // red-50/50
  static const Color editLovedOneAddCustomDislikeBorder = Color(0x80FECACA);

  // --- Loved One Details screen (React LovedOneDetailsScreen) ---
  static const Color lovedOneDetailsHeaderStart = Color(0xFFFB7185);   // rose-400
  static const Color lovedOneDetailsHeaderEnd = Color(0xFFF472B6);     // pink-400
  static const Color lovedOneDetailsBackIcon = Color(0xFFFFFFFF);
  static const Color lovedOneDetailsAvatarBg = Color(0x33FFFFFF);       // white/20
  static const Color lovedOneDetailsName = Color(0xFFFFFFFF);
  static const Color lovedOneDetailsRelationship = Color(0xCCFFFFFF);  // white/80
  static const Color lovedOneDetailsEditBtnBg = Color(0x33FFFFFF);      // white/20
  static const Color lovedOneDetailsEditIcon = Color(0xFFFFFFFF);
  static const Color lovedOneDetailsCardBg = Color(0xCCFFFFFF);         // white/80 (RomanticCard)
  static const Color lovedOneDetailsCardTitle = Color(0xFF374151);      // gray-700
  static const Color lovedOneDetailsSectionIcon = Color(0xFFFB7185);   // rose-400
  static const Color lovedOneDetailsRowLabel = Color(0xFF6B7280);      // gray-500
  static const Color lovedOneDetailsRowValue = Color(0xFF1F2937);      // gray-800
  static const Color lovedOneDetailsContactBubbleBg = Color(0xFFF3F4F6); // gray-100
  static const Color lovedOneDetailsContactBubbleIcon = Color(0xFF4B5563);
  static const Color lovedOneDetailsPrimaryGoalLabel = Color(0xFF4B5563);
  static const Color lovedOneDetailsPrimaryGoalBorder = Color(0xFFFBCFE8); // pink-200
  static const Color lovedOneDetailsPrimaryGoalDesc = Color(0xFF6B7280);
  static const Color lovedOneDetailsSecondaryPillBg = Color(0xFFF3E8FF);   // purple-100
  static const Color lovedOneDetailsSecondaryPillText = Color(0xFF7C3AED);  // purple-700
  static const Color lovedOneDetailsSecondaryRowSelectedBorder = Color(0xFFFB7185);
  static const Color lovedOneDetailsSecondaryRowSelectedBgStart = Color(0xFFFFF1F2);
  static const Color lovedOneDetailsSecondaryRowSelectedBgEnd = Color(0xFFFDF2F8);
  static const Color lovedOneDetailsSecondaryRowUnselectedBorder = Color(0xFFFBCFE8);
  static const Color lovedOneDetailsSecondaryRowDisabledBg = Color(0xFFF9FAFB);
  static const Color lovedOneDetailsChipBg = Color(0xFFFFF1F2);        // rose-50
  static const Color lovedOneDetailsChipText = Color(0xFFBE185D);       // rose-700
  static const Color lovedOneDetailsChipBorderSelected = Color(0xFFFB7185);
  static const Color lovedOneDetailsChipBorderUnselected = Color(0xFFE5E7EB);
  static const Color lovedOneDetailsPremiumCardBgStart = Color(0xFFFAF5FF);
  static const Color lovedOneDetailsPremiumCardBgMid = Color(0xFFFDF2F8);
  static const Color lovedOneDetailsPremiumCardBgEnd = Color(0xFFFFF1F2);
  static const Color lovedOneDetailsPremiumCardBorder = Color(0xFFE9D5FF);
  static const Color lovedOneDetailsPremiumCrownBgStart = Color(0xFFA78BFA);
  static const Color lovedOneDetailsPremiumCrownBgEnd = Color(0xFFEC4899);
  static const Color lovedOneDetailsPremiumTitle = Color(0xFF1F2937);
  static const Color lovedOneDetailsPremiumSubtitle = Color(0xFF6B7280);
  static const Color lovedOneDetailsPremiumHintBg = Color(0xFFF3F4F6);
  static const Color lovedOneDetailsPremiumHintText = Color(0xFF374151);

  // --- Business Onboarding (Business Information) ---
  static const Color businessInfoPageBgStart = Color(0xFFFDF5F8);
  static const Color businessInfoPageBgEnd = Color(0xFFF5F3FF);
  static const Color businessInfoBackBtnBg = Color(0xCCFFFFFF);
  static const Color businessInfoBackIcon = Color(0xFF9333EA);
  static const Color businessInfoBadgeStart = Color(0xFFA78BFA);
  static const Color businessInfoBadgeEnd = Color(0xFF818CF8);
  static const Color businessInfoTitle = Color(0xFF1F2937);
  static const Color businessInfoSubtitle = Color(0xFF9333EA);
  static const Color businessInfoLabel = Color(0xFF6B21A8);
  static const Color businessInfoHelper = Color(0xFF9333EA);
  static const Color businessInfoInputBg = Color(0x99FFFFFF);
  static const Color businessInfoInputBorder = Color(0xFFE9D5FF);
  static const Color businessInfoInputFocusBorder = Color(0xFFC4B5FD);
  static const Color businessInfoInputText = Color(0xFF374151);
  static const Color businessInfoPlaceholder = Color(0xFFD8B4FE);
  static const Color businessInfoDeliveryCardBg = Color(0x99FFFFFF);
  static const Color businessInfoDeliveryCardBorder = Color(0xFFE9D5FF);
  static const Color businessInfoDeliveryCardSelectedBgStart = Color(0xFFFAF5FF);
  static const Color businessInfoDeliveryCardSelectedBgEnd = Color(0xFFEEF2FF);
  static const Color businessInfoDeliveryCardSelectedBorder = Color(0xFFC4B5FD);
  static const Color businessInfoDeliveryIcon = Color(0xFFA855F7);
  static const Color businessInfoDeliveryTitleSelected = Color(0xFF6B21A8);
  static const Color businessInfoDeliveryTitle = Color(0xFF374151);
  static const Color businessInfoDeliveryDesc = Color(0xFF6B7280);
  static const Color businessInfoPriceBadgeBgStart = Color(0x80FAF5FF);
  static const Color businessInfoPriceBadgeBgEnd = Color(0x80EEF2FF);
  static const Color businessInfoPriceBadgeBorder = Color(0xFFE9D5FF);
  static const Color businessInfoPriceBadgeText = Color(0xFF6B21A8);
  static const Color businessInfoUploadBorder = Color(0xFFC4B5FD);
  static const Color businessInfoUploadIconBgStart = Color(0xFFF3E8FF);
  static const Color businessInfoUploadIconBgEnd = Color(0xFFE0E7FF);
  static const Color businessInfoUploadIcon = Color(0xFFA78BFA);
  static const Color businessInfoUploadText = Color(0xFF9333EA);
  static const Color businessInfoSocialCardBgStart = Color(0x66FAF5FF);
  static const Color businessInfoSocialCardBgEnd = Color(0x66FDF2F8);
  static const Color businessInfoSocialCardBorder = Color(0xFFE9D5FF);
  static const Color businessInfoSocialInputBg = Color(0xCCFFFFFF);
  static const Color businessInfoAddLocationBorder = Color(0xFFE9D5FF);
  static const Color businessInfoAddLocationBg = Color(0x66FFFFFF);
  static const Color businessInfoAddLocationText = Color(0xFF9333EA);
  static const Color businessInfoUpgradeCardBgStart = Color(0xFFFAF5FF);
  static const Color businessInfoUpgradeCardBgEnd = Color(0xFFEEF2FF);
  static const Color businessInfoUpgradeCardBorder = Color(0xFFE9D5FF);
  static const Color businessInfoUpgradeText = Color(0xFF6B21A8);
  static const Color businessInfoViewPlansBtnStart = Color(0xFFA78BFA);
  static const Color businessInfoViewPlansBtnEnd = Color(0xFF818CF8);
  static const Color businessInfoSliderActive = Color(0xFF10B981);
  static const Color businessInfoSliderInactive = Color(0xFFE5E7EB);
  static const Color businessInfoSliderThumbStart = Color(0xFFA855F7);
  static const Color businessInfoSliderThumbEnd = Color(0xFFEC4899);

  // --- Business Dashboard (Business Account Profile) ---
  static const Color businessDashboardPageBgStart = Color(0x4DFAF5FF); // purple-50/30
  static const Color businessDashboardPageBgEnd = Color(0xFFFFFFFF);
  static const Color businessDashboardBackBtnBg = Color(0xFFFFFFFF);
  static const Color businessDashboardBackIcon = Color(0xFF9333EA);   // purple-600
  static const Color businessDashboardSettingsBtnBg = Color(0x33FFFFFF); // white/20
  static const Color businessDashboardSettingsBtnBorder = Color(0x4DFFFFFF);
  static const Color businessDashboardProfileBorder = Color(0x80FFFFFF);
  static const Color businessDashboardBadgeBg = Color(0x33A78BFA);   // purple-400/20
  static const Color businessDashboardBadgeText = Color(0xFFE9D5FF); // purple-100
  static const Color businessDashboardStatBoxBg = Color(0x1AFFFFFF);
  static const Color businessDashboardStatBoxBorder = Color(0x33FFFFFF);
  static const Color businessDashboardStatLabel = Color(0xB3FFFFFF);  // white/70
  static const Color businessDashboardStatValue = Color(0xFFFFFFFF);
  static const Color businessDashboardCardBg = Color(0xCCFFFFFF);    // white/80
  static const Color businessDashboardCardDeco = Color(0xFFFAF5FF);  // purple-50
  static const Color businessDashboardMetricLabel = Color(0xFF6B7280);
  static const Color businessDashboardMetricValue = Color(0xFF1F2937);
  static const Color businessDashboardTrendGreen = Color(0xFF16A34A);
  static const Color businessDashboardSectionTitle = Color(0xFF1F2937);
  static const Color businessDashboardSectionSubtitle = Color(0xFF6B7280);
  static const Color businessDashboardManageLink = Color(0xFFA855F7);
  static const Color businessDashboardEmptyIconBg = Color(0xFFFAF5FF);
  static const Color businessDashboardEmptyIcon = Color(0xFFD8B4FE);
  static const Color businessDashboardEmptyTitle = Color(0xFF374151);
  static const Color businessDashboardEmptyDesc = Color(0xFF6B7280);
  static const Color businessDashboardUpgradeCardBgStart = Color(0x80FFE4E6);
  static const Color businessDashboardUpgradeCardBgEnd = Color(0x80FCE7F3);
  static const Color businessDashboardCrownBgStart = Color(0xFFFBBF24);
  static const Color businessDashboardCrownBgEnd = Color(0xFFFB923C);
  static const Color businessDashboardUpgradeTitle = Color(0xFF1F2937);
  static const Color businessDashboardUpgradeDesc = Color(0xFF4B5563);
  static const Color businessDashboardUpgradeDescMuted = Color(0xFF6B7280);
  static const Color businessDashboardSparkleAmber = Color(0xFFF59E0B);
}
