// lib/app/theme/app_colors.dart
import 'package:flutter/material.dart';

/// Design tokens for colors. Extracted from React SplashScreen computed/source.
abstract class AppColors {
  // --- Splash / Marketing palette ---
  static const Color splashBgStart = Color(0xFFFFFBFC);
  static const Color splashBg25 = Color(0xFFFFF5F7);
  static const Color splashBg50 = Color(0xFFFFEFF3);
  static const Color splashBg75 = Color(0xFFFCE8ED);
  static const Color splashBgEnd = Color(0xFFF5E0E7);

  static const Color primaryPink = Color(0xFFE91E63);
  static const Color primaryPurple = Color(0xFF9C27B0);
  static const Color pinkDark = Color(0xFFC2185B);
  static const Color purpleDark = Color(0xFF7B1FA2);
  static const Color pinkAccent = Color(0xFFF06292);
  static const Color pinkLight = Color(0xFFF48FB1);
  static const Color purpleAccent = Color(0xFFBA68C8);

  static const Color textPrimary = Color(0xFF4A1942);
  static const Color textSecondary = Color(0xFF6B2C4D);
  static const Color textMuted = Color(0xFF9C7B8A);

  static const Color success = Color(0xFF10B981);

  static const Color white = Color(0xFFFFFFFF);
  static const Color white70 = Color(0xB3FFFFFF);
  static const Color white60 = Color(0x99FFFFFF);
  static const Color white40 = Color(0x66FFFFFF);

  // --- Onboarding Intro (HeroBannerDemo) ---
  static const Color onboardingPageBg = Color(0xFFFFFFFF);
  static const Color onboardingHeadline = Color(0xFF7A3E55);
  static const Color onboardingBulletText = Color(0xFFA84968);
  static const Color onboardingSubtext = Color(0xFF8B4A65);
  static const Color onboardingThatsAll = Color(0xFFB05A78);
  static const Color onboardingValuePropRed = Color(0xFFE11D48);
  static const Color onboardingValuePropPink = Color(0xFFEC4899);
  static const Color onboardingValuePropPurple = Color(0xFFA855F7);
  static const Color onboardingPinkFill = Color(0xFFF9A8D4);
  static const Color onboardingRoseFill = Color(0xFFFB7185);
  static const Color onboardingCardBorder = Color(0x4DFBCFE8);
  static const Color onboardingCardBorderStrong = Color(0x80FB7185);
  static const Color onboardingGlobeBorder = Color(0x66FBCFE8);

  // --- Auth (Sign Up / Login) ---
  static const Color authBackBg = Color(0xFFEFE8FF);
  static const Color authWelcomeTitle = Color(0xFFE22B69);
  static const Color authSubtitle = Color(0xFF333333);
  static const Color authTabContainerBg = Color(0xFFF8F8F8);
  static const Color authTabInactiveText = Color(0xFF333333);
  static const Color authSocialButtonBg = Color(0xFFFFFFFF);
  static const Color authSocialButtonText = Color(0xFF333333);
  static const Color authDividerLine = Color(0xFFE5E5E5);
  static const Color authDividerText = Color(0xFFAAAAAA);
  static const Color authInputBg = Color(0xFFFFF2F6);
  static const Color authInputPlaceholder = Color(0xFFF28BA8);
  static const Color authInputBorder = Color(0xFFFECDD3);
  static const Color authInputFocusBorder = Color(0xFFE91E63);
  static const Color authFooterText = Color(0xB3666666);
  static const Color authErrorBg = Color(0xFFFEF2F2);
  static const Color authErrorBorder = Color(0xFFFECACA);
  static const Color authErrorText = Color(0xFFB91C1C);

  // --- User Type selection ---
  static const Color userTypeBgStart = Color(0xFFF3E8FF);
  static const Color userTypeBgMid = Color(0xFFFDF2F8);
  static const Color userTypeBgEnd = Color(0xFFFFE4E6);
  static const Color userTypeTitle = Color(0xFF6B21A8);
  static const Color userTypeTitleAccent = Color(0xFFE11D48);
  static const Color userTypeSubtitle = Color(0xFFF43F5E);
  static const Color userTypeCardBg = Color(0xCCFFFFFF);
  static const Color userTypeCardTitle = Color(0xFF6B21A8);
  static const Color userTypeCardDesc = Color(0xFF374151);
  static const Color userTypeCardBorder = Color(0x99FDA4AF);
  static const Color userTypeCardBorderSelected = Color(0xB3FB7185);
  static const Color userTypeCardBorderBusiness = Color(0x99C4B5FD);
  static const Color userTypeCardBorderBusinessSelected = Color(0xB3A78BFA);

  // --- Individual Profile Step 1 (Tell Cherish AI about yourself) ---
  static const Color profileStep1BgTop = Color(0xFFFBEFFF);
  static const Color profileStep1BgMid = Color(0xFFFDF5F8);
  static const Color profileStep1BgBottom = Color(0xFFFCEEF3);
  static const Color profileStep1BackBtnBg = Color(0xFFFFF2F6);
  static const Color profileStep1BackBtnIcon = Color(0xFFFB7185);
  static const Color profileStep1StepPillText = Color(0xFFFB7185);
  static const Color profileStep1Title = Color(0xFF1E293B);
  static const Color profileStep1Subtitle = Color(0xFF6B7280);
  static const Color profileStep1Label = Color(0xFF6B7280);
  static const Color profileStep1CardBg = Color(0xFFFFFFFF);
  static const Color profileStep1CardLabel = Color(0xFF1E293B);
  static const Color profileStep1RequiredAsterisk = Color(0xFFDC2626);
  static const Color profileStep1Helper = Color(0xFF9CA3AF);
  static const Color profileStep1InputBg = Color(0xFFFFFFFF);
  static const Color profileStep1InputBorder = Color(0xFFE5E7EB);
  static const Color profileStep1InputPlaceholder = Color(0xFF9CA3AF);
  static const Color profileStep1ChipText = Color(0xFF374151);
  static const Color profileStep1ChipBorder = Color(0xFFE5E7EB);
  static const Color profileStep1ChipSelectedBg = Color(0xFFFB7185);
  static const Color profileStep1PhotoCircleBorder = Color(0xFFFFC0CB);
  static const Color profileStep1PhotoCircleInner = Color(0xFFFFF2F6);
  static const Color profileStep1PhotoIcon = Color(0xFFFB7185);
  static const Color profileStep1RequiredHint = Color(0xFFDC2626);

  // --- Individual Step 2 (Add a loved one) ---
  static const Color lovedOneBgTop = Color(0xFFFDF2F8);
  static const Color lovedOneBgBottom = Color(0xFFFCE7F3);
  static const Color lovedOneBackBtnBg = Color(0xFFFFF2F6);
  static const Color lovedOneBackBtnIcon = Color(0xFFFB7185);
  static const Color lovedOneHeartCircleBg = Color(0xFFFB7185);
  static const Color lovedOneTitle = Color(0xFF1E293B);
  static const Color lovedOneSubtitle = Color(0xFFE11D48);
  static const Color lovedOnePhotoLabel = Color(0xFFFB7185);
  static const Color lovedOnePhotoCircleBg = Color(0xFFFFF2F6);
  static const Color lovedOnePhotoCircleBorder = Color(0xFFF9A8D4);
  static const Color lovedOnePhotoIcon = Color(0xFF64748B);
  static const Color lovedOneCardLabel = Color(0xFF1E293B);
  static const Color lovedOneRequiredAsterisk = Color(0xFFDC2626);
  static const Color lovedOneInputBg = Color(0xFFFFF2F6);
  static const Color lovedOneInputBorder = Color(0xFFE5E7EB);
  static const Color lovedOneInputPlaceholder = Color(0xFF9CA3AF);
  static const Color lovedOneSectionCardBg = Color(0xFFF8F8F8);
  static const Color lovedOneTileBg = Color(0xFFFFFFFF);
  static const Color lovedOneTileBorder = Color(0xFFE5E7EB);
  static const Color lovedOneTileText = Color(0xFF374151);
  static const Color lovedOneTileSelectedBg = Color(0xFFFFF2F6);
  static const Color lovedOneTileSelectedBorder = Color(0xFFFB7185);

  // --- Individual Step 3 (Your relationship goals) ---
  static const Color goalsBgTop = Color(0xFFFDF5F8);
  static const Color goalsBgBottom = Color(0xFFFAFAFA);
  static const Color goalsBackBtnBg = Color(0xFFFFFFFF);
  static const Color goalsBackBtnIcon = Color(0xFF374151);
  static const Color goalsTargetCircleBg = Color(0xFFBE185D);
  static const Color goalsTargetIcon = Color(0xFFFFFFFF);
  static const Color goalsTitle = Color(0xFF1E293B);
  static const Color goalsDescription = Color(0xFF6B7280);
  static const Color goalsSectionLabel = Color(0xFF1E293B);
  static const Color goalsCardBg = Color(0xFFFFFFFF);
  static const Color goalsCardTitle = Color(0xFF1E293B);
  static const Color goalsCardSubtitle = Color(0xFF6B7280);
  static const Color goalsSaveDisabledBg = Color(0xFFE5E7EB);
  static const Color goalsSaveDisabledText = Color(0xFF9CA3AF);
  static const Color goalsSaveEnabledText = Color(0xFFFFFFFF);
  static const Color goalsFooterText = Color(0xFF9CA3AF);
  static const Color goalsCardIconBgPink = Color(0xFFFFE4EC);
  static const Color goalsCardIconPink = Color(0xFFFB7185);
  static const Color goalsCardIconBgOrange = Color(0xFFFFEDD5);
  static const Color goalsCardIconOrange = Color(0xFFF97316);
  static const Color goalsCardIconBgBlue = Color(0xFFDBEAFE);
  static const Color goalsCardIconBlue = Color(0xFF3B82F6);
  static const Color goalsCardIconBgPurple = Color(0xFFE9D5FF);
  static const Color goalsCardIconPurple = Color(0xFFA855F7);
  static const Color goalsCardIconBgYellow = Color(0xFFFEF3C7);
  static const Color goalsCardIconYellow = Color(0xFFF59E0B);
  static const Color goalsCardIconBgRed = Color(0xFFFEE2E2);
  static const Color goalsCardIconRed = Color(0xFFEF4444);

  // --- Individual Step 4 (Secondary Relationship Goals) ---
  static const Color secGoalsBgTop = Color(0xFFFFFFFF);
  static const Color secGoalsBgBottom = Color(0xFFFDF2F8);
  static const Color secGoalsBackBtnBg = Color(0xFFF9FAFB);
  static const Color secGoalsBackBtnIcon = Color(0xFFA855F7);
  static const Color secGoalsTitle = Color(0xFF1E293B);
  static const Color secGoalsSubtitle = Color(0xFFE11D48);
  static const Color secGoalsDescription = Color(0xFF6B7280);
  static const Color secGoalsPillBg = Color(0xFFFFFFFF);
  static const Color secGoalsPillBorder = Color(0xFFFBCFE8);
  static const Color secGoalsPillText = Color(0xFF1E293B);
  static const Color secGoalsSectionBubbleBeige = Color(0xFFFEF3C7);
  static const Color secGoalsSectionBubbleBlue = Color(0xFFDBEAFE);
  static const Color secGoalsSectionBubblePink = Color(0xFFFFE4EC);
  static const Color secGoalsSectionBubbleYellow = Color(0xFFFEF9C3);
  static const Color secGoalsSectionTitle = Color(0xFF1E293B);
  static const Color secGoalsOptionCardBg = Color(0xFFFFFFFF);
  static const Color secGoalsOptionCardBorder = Color(0xFFFBCFE8);
  static const Color secGoalsOptionText = Color(0xFF6B7280);
  static const Color secGoalsSelectorBorder = Color(0xFFD1D5DB);
  static const Color secGoalsSelectorSelected = Color(0xFFFB7185);
  static const Color secGoalsCtaDisabledBg = Color(0xFFE5E7EB);
  static const Color secGoalsCtaDisabledText = Color(0xFF9CA3AF);
  static const Color secGoalsSkipLink = Color(0xFFA855F7);

  // --- Loved One Preferences ---
  static const Color prefsBgTop = Color(0xFFFDF5F8);
  static const Color prefsBgBottom = Color(0xFFF5F3FF);
  static const Color prefsBackBtnBg = Color(0xFFF3E8FF);
  static const Color prefsBackBtnIcon = Color(0xFFA855F7);
  static const Color prefsProgressInactive = Color(0xFFE9D5FF);
  static const Color prefsProgressActive = Color(0xFFA855F7);
  static const Color prefsOptionalPillBg = Color(0xFFF3E8FF);
  static const Color prefsOptionalPillText = Color(0xFF7C3AED);
  static const Color prefsTitle = Color(0xFF1E293B);
  static const Color prefsSubtitle = Color(0xFF6B7280);
  static const Color prefsSectionBubbleBg = Color(0xFFF5F3FF);
  static const Color prefsSectionTitle = Color(0xFF1E293B);
  static const Color prefsSectionDesc = Color(0xFF6B7280);
  static const Color prefsAddButtonBorder = Color(0xFFF9A8D4);
  static const Color prefsAddButtonText = Color(0xFFEC4899);
  static const Color prefsChipBg = Color(0xFFFFFFFF);
  static const Color prefsChipBorder = Color(0xFFE5E7EB);
  static const Color prefsChipText = Color(0xFF374151);
  static const Color prefsChipSelectedBg = Color(0xFFFFF2F6);
  static const Color prefsChipSelectedBorder = Color(0xFFFB7185);
  static const Color prefsCategoryCardCreative = Color(0xFFFDF2F8);
  static const Color prefsCategoryCardFood = Color(0xFFFEFCE8);
  static const Color prefsCategoryCardExperiences = Color(0xFFECFDF5);
  static const Color prefsCategoryCardWellness = Color(0xFFDCFCE7);
  static const Color prefsCategoryCardFun = Color(0xFFF3E8FF);
  static const Color prefsCategoryCardAmbition = Color(0xFFEFF6FF);
  static const Color prefsCategoryCardRelationships = Color(0xFFFFF2F6);
  static const Color prefsCategoryCardTech = Color(0xFFF9FAFB);

  // --- Dislikes screen ---
  static const Color dislikesBgTop = Color(0xFFFDF8F9);
  static const Color dislikesBgBottom = Color(0xFFFAFAF9);
  static const Color dislikesBackText = Color(0xFFBE185D);
  static const Color dislikesProgressActive = Color(0xFFE11D48);
  static const Color dislikesProgressInactive = Color(0xFFFBCFE8);
  static const Color dislikesFinalPillBg = Color(0xFFFFF1F2);
  static const Color dislikesFinalPillBorder = Color(0xFFFECDD3);
  static const Color dislikesFinalPillText = Color(0xFFE11D48);
  static const Color dislikesTitle = Color(0xFFC2410C);
  static const Color dislikesDesc = Color(0xFF1E293B);
  static const Color dislikesOptional = Color(0xFFA855F7);
  static const Color dislikesCardGift = Color(0xFFFFF7ED);
  static const Color dislikesCardFood = Color(0xFFFFFBEB);
  static const Color dislikesCardExperiences = Color(0xFFFEF3C7);
  static const Color dislikesCardWellness = Color(0xFFF1F5F9);
  static const Color dislikesCategoryTitle = Color(0xFF1E293B);
  static const Color dislikesChipBg = Color(0xFFFAFAFA);
  static const Color dislikesChipBorder = Color(0xFFE5E7EB);
  static const Color dislikesChipText = Color(0xFF374151);
  static const Color dislikesChipSelectedBg = Color(0xFFFFF2F6);
  static const Color dislikesChipSelectedBorder = Color(0xFFFB7185);
  static const Color dislikesAddButtonBg = Color(0xFFFFFFFF);
  static const Color dislikesAddButtonBorder = Color(0xFFE5E7EB);
  static const Color dislikesAddButtonText = Color(0xFF374151);
  static const Color dislikesHelperText = Color(0xFF9CA3AF);

  // --- Personal Note (Add a Personal Note) ---
  static const Color noteBgTop = Color(0xFFFDF5F8);
  static const Color noteBgBottom = Color(0xFFFFFFFF);
  static const Color noteBackText = Color(0xFFBE185D);
  static const Color noteSkipText = Color(0xFF6B7280);
  static const Color noteLogoHeartBg = Color(0xFFEC4899);
  static const Color noteLogoText = Color(0xFFBE185D);
  static const Color noteUnderline = Color(0xFFF472B6);
  static const Color noteProgressBg = Color(0xFFFBCFE8);
  static const Color noteProgressFill = Color(0xFFE11D48);
  static const Color noteStepLabel = Color(0xFF6B7280);
  static const Color noteBubbleBg = Color(0xFFF3E8FF);
  static const Color noteTitle = Color(0xFF1E293B);
  static const Color noteSubtitle = Color(0xFF374151);
  static const Color noteCardBg = Color(0xFFFFFFFF);
  static const Color noteLabelText = Color(0xFF1E293B);
  static const Color noteRequiredAsterisk = Color(0xFFDC2626);
  static const Color noteThumbsUpIcon = Color(0xFFF59E0B);
  static const Color noteInputBorder = Color(0xFFE5E7EB);
  static const Color noteInputPlaceholder = Color(0xFF9CA3AF);
  static const Color noteCounter = Color(0xFF9CA3AF);
  static const Color noteHelperBoxBg = Color(0xFFF5F3FF);
  static const Color noteHelperText = Color(0xFF374151);
  static const Color noteSeeMoreText = Color(0xFFBE185D);
  static const Color noteSeeMoreIcon = Color(0xFFE11D48);
  static const Color noteCtaDisabledBg = Color(0xFFE5E7EB);
  static const Color noteCtaText = Color(0xFFFFFFFF);

  // --- Subscription (Choose your plan) ---
  static const Color subPageBgTop = Color(0xFFFDF5F8);
  static const Color subPageBgBottom = Color(0xFFFFFFFF);
  static const Color subBackText = Color(0xFFBE185D);
  static const Color subTitle = Color(0xFFBE185D);
  static const Color subSubtitle = Color(0xFF374151);
  static const Color subActiveCardBg = Color(0xFFFFF1F2);
  static const Color subActiveCardBorder = Color(0xFFFECDD3);
  static const Color subActiveLabel = Color(0xFFFB7185);
  static const Color subActiveGreenDot = Color(0xFF22C55E);
  static const Color subActivePlanName = Color(0xFFBE185D);
  static const Color subActiveRenewal = Color(0xFF6B7280);
  static const Color subCurrentBadgeBg = Color(0xFFFFF1F2);
  static const Color subCurrentBadgeText = Color(0xFFBE185D);
  static const Color subCancelLink = Color(0xFFEC4899);
  static const Color subCardBg = Color(0xFFFFFFFF);
  static const Color subCardBorder = Color(0xFFFBCFE8);
  static const Color subPlanName = Color(0xFFBE185D);
  static const Color subPlanSubtitle = Color(0xFF6B7280);
  static const Color subPriceMain = Color(0xFFBE185D);
  static const Color subPricePeriod = Color(0xFF6B7280);
  static const Color subSectionLabel = Color(0xFFFB7185);
  static const Color subIncludeText = Color(0xFF374151);
  static const Color subIncludeDetail = Color(0xFF9CA3AF);
  static const Color subBestFor = Color(0xFF6B7280);
  static const Color subCtaText = Color(0xFFFFFFFF);
  static const Color subRecPillText = Color(0xFFFFFFFF);

  // --- Checkout (Complete Your Order) ---
  static const Color checkoutPageBgTop = Color(0xFFFDF5F8);
  static const Color checkoutPageBgBottom = Color(0xFFFFFFFF);
  static const Color checkoutBackText = Color(0xFFBE185D);
  static const Color checkoutSecureBg = Color(0xFFD1FAE5);
  static const Color checkoutSecureBorder = Color(0xFF6EE7B7);
  static const Color checkoutSecureText = Color(0xFF047857);
  static const Color checkoutSecureIcon = Color(0xFF059669);
  static const Color checkoutTitle = Color(0xFF1E293B);
  static const Color checkoutSubtitle = Color(0xFF6B7280);
  static const Color checkoutCardBg = Color(0xFFFFFFFF);
  static const Color checkoutCardBorder = Color(0xFFFBCFE8);
  static const Color checkoutSectionTitle = Color(0xFF1E293B);
  static const Color checkoutIconSquarePink = Color(0xFFFB7185);
  static const Color checkoutIconSquarePurple = Color(0xFFA855F7);
  static const Color checkoutInputBg = Color(0xFFF9FAFB);
  static const Color checkoutInputBorder = Color(0xFFE5E7EB);
  static const Color checkoutInputPlaceholder = Color(0xFF9CA3AF);
  static const Color checkoutPaymentTileBorder = Color(0xFFFBCFE8);
  static const Color checkoutPaymentTileSelectedBg = Color(0xFFFFF1F2);
  static const Color checkoutPaymentTileSelectedBorder = Color(0xFFFB7185);
  static const Color checkoutPaymentTileSelectedText = Color(0xFFBE185D);
  static const Color checkoutPaymentTileDot = Color(0xFFEC4899);
  static const Color checkoutPaymentTileUnselectedText = Color(0xFF374151);
  static const Color checkoutSecurityBoxBg = Color(0xFFECFDF5);
  static const Color checkoutSecurityBoxBorder = Color(0xFFA7F3D0);
  static const Color checkoutSecurityBoxTitle = Color(0xFF065F46);
  static const Color checkoutSecurityBoxDesc = Color(0xFF047857);
  static const Color checkoutOrderPlanName = Color(0xFF1E293B);
  static const Color checkoutOrderPricePeriod = Color(0xFF6B7280);
  static const Color checkoutDueTodayLabel = Color(0xFF1E293B);
  static const Color checkoutDisclaimerBg = Color(0xFFF3F4F6);
  static const Color checkoutDisclaimerText = Color(0xFF6B7280);
  static const Color checkoutCtaText = Color(0xFFFFFFFF);
  static const Color checkoutFooterCheck = Color(0xFF059669);
  static const Color checkoutFooterText = Color(0xFF374151);
}
